#ifdef REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS
#undef REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS
#endif

#ifdef REF_COUNTED_SHARED_PTR_STD
#ifdef REF_COUNTED_SHARED_PTR_BOOST
#define REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS(...) \
REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS_STD( __VA_ARGS__ ); \
REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS_BOOST( __VA_ARGS__ )
#else
#define REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS(...) \
REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS_STD( __VA_ARGS__ )
#endif
#elif defined(REF_COUNTED_SHARED_PTR_BOOST)
#define REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS(...) \
REF_COUNTED_SHARED_PTR_DEFINE_PRIVATE_ACCESSORS_BOOST( __VA_ARGS__ )
#endif
